### ISSUE TITLE
Image Lightbox Styles

### ISSUE THREAD

**Issue by devonashleyberger** [rgbdev/contacts#106]
Update icons and placement
Loading spinner is unique

**Comment by devonashleyberger** [comment]
@tim-phillips 

I'd like to replace icons and update the layout of the light box. Where can I find the css and svgs?

**Comment by tim-phillips** [comment]
Are you able to override the css in [css/style.css](https://github.com/rgbdev/contacts/blob/master/css/style.css)?

How important is it that we can use our own svgs? They're baked into the library. We'd have to fork it and replace the svgs with our own.

**Comment by devonashleyberger** [comment]
do #119 with this

**Comment by tim-phillips** [comment]
I don't think it is related, it's regarding the pointer on the thumbnails. I edited the title to clarify.

<img width="168" alt="screen shot 2018-05-23 at 8 10 17 pm" src="https://user-images.githubusercontent.com/3578574/40462569-5aa803d2-5ec5-11e8-9503-3ef8c9aadf64.png">

**Comment by devonashleyberger** [comment]
I killed the close icon. If the spinner is too hard to switch out, we can close this issue @tim-phillips
