### ISSUE TITLE
Contact page most recent production

### ISSUE THREAD

**Issue by devonashleyberger** [rgbdev/contacts#124]
make this:
<img width="411" alt="screen shot 2018-05-23 at 5 42 50 pm" src="https://user-images.githubusercontent.com/3409198/40458445-de29cf2a-5eb0-11e8-815d-56f4a05ca5b4.png">

look like this:
<img width="322" alt="screen shot 2018-05-23 at 5 43 12 pm" src="https://user-images.githubusercontent.com/3409198/40458447-e5d6cc1e-5eb0-11e8-8650-1e8a38aa182a.png">

**Comment by tim-phillips** [comment]
It's built, just needs to be styled
