### ISSUE TITLE
No production history response

### ISSUE THREAD

**Issue by devonashleyberger** [rgbdev/contacts#88]
Style the span

**Comment by tim-phillips** [comment]
Here's the element in case you need to change it / add a `className`

https://github.com/rgbdev/contacts/blob/6e040bb1cdf59617c56f3568da0b47519d70dd1c/pages/production-list.js#L33

**Comment by devonashleyberger** [comment]
I'd like to go back on my decision here: 

What do you think of making this a disabled button? The disabled button would read, "No production history" or something. I think it would be a better experience.

**Comment by devonashleyberger** [comment]
Ok. Should read "No Production History" and have class="disabled" applied

Pull request #96 has the styles
