### ISSUE TITLE
Loading indicator on a contact's "Personal" tab

### ISSUE THREAD

**Issue by devonashleyberger** [rgbdev/contacts#98]
Use the same behavior as "Professional" tab (#91)

**Comment by devonashleyberger** [comment]
<img width="476" alt="screen shot 2018-05-17 at 4 48 42 pm" src="https://user-images.githubusercontent.com/3409198/40209096-4f445680-59f2-11e8-84e1-2f2a84c69e52.png">

**Comment by tim-phillips** [comment]
I'll dynamically load the entire `Personal` component and use the `Spinner` as the loading component
